apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # Name of the ExternalSecret resource
  name: {{ .Values.name }}
  # Kubernetes namespace where the ExternalSecret will be created
  namespace: {{ .Values.namespace }}
spec:
  # How often the secret should be refreshed
  refreshInterval: {{ .Values.refreshInterval }}
  # Reference to the SecretStore resource
  secretStoreRef:
    # Name of the SecretStore (configured separately)
    name: {{ .Values.secretStoreName }}
    # Type of the SecretStore (default is SecretStore, but ClusterSecretStore can also be used)
    kind: SecretStore
  target:
    # Name of the Kubernetes Secret where the extracted secrets will be stored
    name: {{ .Values.secretName }}
  # Extract all key-value pairs from the referenced secret in the external secret manager
  dataFrom:
    - extract:
        # Path to the external secret in the secret manager
        key: {{ .Values.secretManagerRef }}