{{- if .Values.env.external_secret.create }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.deployment.name}}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.env.external_secret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.env.external_secret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.env.external_secret.secretName }}
  dataFrom:
    - extract:
        key: {{ .Values.env.external_secret.secretManagerRef}}
{{- end }}
